services:
    beerfestivaldb:
        image: mariadb:10.6
        container_name: beerfestivaldb
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: beerdb
            MYSQL_USER: beeruser
            MYSQL_PASSWORD: beerpassword
        ports:
            - "3306:3306"
        volumes:
            - mariadb_data:/var/lib/mysql
            - ./init-scripts:/docker-entrypoint-initdb.d
        restart: unless-stopped
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
    mariadb_data:
  